v0.1.0

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,35 +1,75 @@
+sudo: required
 language : 
   - go  
+
+services:
+  - docker
+os:
+  - linux
+#  - osx
+#  - windows
+  
+cache:
+  bundler: false
+  directories:
+  - .build-cache          # images.txt
+# Handle git submodules yourself
+git:
+    submodules: false
+# Do a github login using token
 before_install:
   - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
- 
-os: 
-  - linux
-  - osx
-  - windows
-branches:
-  only:
-    - master
 install:
-  - go get github.com/constabulary/gb/...
   - go get -u github.com/constabulary/gb/...
-#  - go get github.com/TIBCOSoftware/flogo-cli/...
-#  - go get -u github.com/TIBCOSoftware/flogo-cli/...
-  - go get github.com/TIBCOSoftware/mashling-cli/...
-  - go get -u github.com/TIBCOSoftware/mashling-cli/...
-  - pwd
-  - cd ../../TIBCOSoftware
-  - git clone https://github.com/LakshmiMekala/recip1.git
-  - cd recip1
-#  - git clone recipe https://github.com/LakshmiMekala/recip1.git
-  - git checkout -b recipe origin/recipe
-  - pushd samples-recipes
-  - ls
+  - go get github.com/TIBCOSoftware/mashling/...
+  - cd $GOPATH/src/github.com/TIBCOSoftware
+  - "git ls-remote --exit-code https://github.com/TIBCOSoftware/mashling-cicd.git ${TRAVIS_BRANCH} ;
+    if [ $? -eq 0 ]; then 
+        echo \"Branch ${TRAVIS_BRANCH} found on mashling-cicd\" ;
+        git clone https://github.com/TIBCOSoftware/mashling-cicd.git --branch ${TRAVIS_BRANCH} --single-branch mashling-cicd ;
+    else 
+        echo \"Branch ${TRAVIS_BRANCH} not found on mashling-cicd using master\" ;
+        git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd ;
+    fi"
+  - pushd mashling-cicd/sample-recipes
+  - rm -rf builds
+  - mkdir -p builds/latest master-builds/latest
+  
 script:
-   - chmod ugo+x ./build-c-new.sh 
-   - ./build-c-new.sh
-   - popd
-
+  - chmod ugo+x ./build-recipes.sh ./sanity.sh ./build-registry-recipes.sh
+  - ./build-recipes.sh
+  - ./sanity.sh
+  - popd
+  - pushd mashling-cicd/sample-recipes
+  - ./build-registry-recipes.sh
+  - popd
+  - cd $GOPATH/src/github.com/TIBCOSoftware/mashling  
+  - touch mashling.tgz
+  - tar cvfz mashling.tgz --exclude=mashling.tgz .
+  - find . -not -name "mashling.tgz" -not  -name "\." -not -name "\.\."  -print0 | xargs -0 rm -rf --
+  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then    
+    pushd mashling-cicd/docker/mashling;
+    chmod ugo+x ./build-mashling.sh ;
+    ./build-mashling.sh ;
+    popd ;
+    fi
+  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then      
+    pushd mashling-cicd/docker/mashling-sample;
+    chmod ugo+x ./build-mashling-sample.sh ;
+    ./build-mashling-sample.sh ;
+    popd ;
+    fi
+    
 after_script:
-  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc" 
+  - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
 
+after_success:
+  - "docker login -u=\"${DOCKER_USERNAME}\" -p=\"${DOCKER_PASSWORD}\" tibdocker.tibco.com"
+  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
+    source ${TRAVIS_BUILD_DIR}/mashling-cicd/scripts/init.sh ;
+    mashling::module::postbuild mashling mashling ;
+    fi"
+  - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
+    source  $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/scripts/init.sh;
+    mashling::module::postbuild mashling-sample mashling-sample ;
+    fi"
